# Generated by Django 4.1.7 on 2023-09-17 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_recipeitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='created_by',
            field=models.ForeignKey(default='himynameisjs', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
