# Generated by Django 4.1.7 on 2023-10-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='author',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='img_src',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
