# Generated by Django 4.1.7 on 2023-12-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeitem_author_alter_recipeitem_img_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredients',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='steps',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
